INFERANALYZE= /usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/../../../bin/InferAnalyze $(INFER_OPTIONS) -results_dir '/Users/Diablo/AndroidStudioProjects/MyLint/infer-out'

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 

default: test

all: test

test: $(CLUSTERS)
	echo ""
#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/BuildConfig.java.b74ce17ae1d46c2bb0adcc292e24ecae
cl1: 
	$(INFERANALYZE) -cluster xcl1.cluster >cl1

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/BuildConfig.java.f4dedd6b84635228797927efe7b3eab2
cl2: 
	$(INFERANALYZE) -cluster xcl2.cluster >cl2

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/BuildConfig.java.fc8c728432c74861da79da37496338e8
cl3: 
	$(INFERANALYZE) -cluster xcl3.cluster >cl3

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/JavaChineseStringDetector.java.33d9147c8cb7fbcaa478bd7ca618fe21
cl4: 
	$(INFERANALYZE) -cluster xcl4.cluster >cl4

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/LogDetector.java.87eff78b01bb6af52111c444362298e2
cl5: 
	$(INFERANALYZE) -cluster xcl5.cluster >cl5

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/MainActivity.java.965e7ceb486477b1f7527f1b9be03667
cl6: 
	$(INFERANALYZE) -cluster xcl6.cluster >cl6

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/MyIssueRegistry.java.c9932e1b3552fbc19d2b672f1aa57d78
cl7: 
	$(INFERANALYZE) -cluster xcl7.cluster >cl7

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/R.java.3c959249dbd25bbb0d8d0b46cb90f13c
cl8: 
	$(INFERANALYZE) -cluster xcl8.cluster >cl8

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/R.java.9233e4466f22f7905622673efcdbee90
cl9: 
	$(INFERANALYZE) -cluster xcl9.cluster >cl9

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/R.java.99ffd166a8154b5ba690dc0366a08c9b
cl10: 
	$(INFERANALYZE) -cluster xcl10.cluster >cl10

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/R.java.abd55d820809972add312118bb8e7997
cl11: 
	$(INFERANALYZE) -cluster xcl11.cluster >cl11

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/R.java.ac7fd46dd9ed85a2b2db7e40f7f23b81
cl12: 
	$(INFERANALYZE) -cluster xcl12.cluster >cl12

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/R.java.c7e52aeb41b8593f15c05f9ece50fcb8
cl13: 
	$(INFERANALYZE) -cluster xcl13.cluster >cl13

#/Users/Diablo/AndroidStudioProjects/MyLint/infer-out/captured/R.java.d7ed72c9375e7a9786a3220984ef602a
cl14: 
	$(INFERANALYZE) -cluster xcl14.cluster >cl14


clean:
	rm -f $(CLUSTERS)
